# -*- coding: utf-8 -*-
"""Day 0-1-2-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LNC0-O7m1QAtPy-u9OgTmqRF7rjG1oud
"""

# Day 0

# Read a full line of input from stdin and save it to our dynamically typed variable, input_string.
input_string = input('Welcome to 30 days of code!')
# Print a string literal saying "Hello, World." to stdout.
print('Hello, World.')

# TODO: Write a line of code here that prints the contents of input_string to stdout.
print(input_string)

# Day 1

i = 4
d = 4.0
s = 'HackerRank '
# Declare second integer, double, and String variables.
a = int(input())
b = float(input()) 
s = input()
# Read and save an integer, double, and String to your variables.

# Print the sum of both integer variables on a new line.
print(i + a)
# Print the sum of the double variables on a new line.
print(i + b)
# Concatenate and print the String variables on a new line
c = 'HackerRank ' + s
# The 's' variable above should be printed first.
print(c)

# Day 2


#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
#def solve(meal_cost, tip_percent, tax_percent):
meal_cost = float(input())
tip_percent = int(input())
tax_percent = int(input())

tip = meal_cost * tip_percent / 100
tax = meal_cost * tax_percent / 100
    
total = meal_cost + tip + tax

totalCost = int(round(total))



print(totalCost)

# Day 3

#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

    if n % 2 == 1:
        print('Weird')
    elif n % 2 == 0 and 2 <= n <= 5 :
        print('Not Weird')
    elif n % 2 == 0 and 6 <= n <= 20:
        print('Weird')
    elif n % 2 == 0 and n > 20:
        print('Not Weird')
    else :
        print('Not Weird')