# -*- coding: utf-8 -*-
"""Hackerrank_30daysofcode_day19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AFRwl0Ta19eFhuiZt3QVX0MGFYHjpLwm
"""

class AdvancedArithmetic(object):
    def divisorSum(n):
        raise NotImplementedError

class Calculator(AdvancedArithmetic):
    def divisorSum(self, n):
        temp = []

        for i in range (1,n+1):
            if n%i == 0:
                temp.append(i)
        return sum(temp)
        

    


n = int(input())
my_calculator = Calculator()
s = my_calculator.divisorSum(n)
print("I implemented: " + type(my_calculator).__bases__[0].__name__)
print(s)