# -*- coding: utf-8 -*-
"""Hackerrank day 10 / 30daysOfCode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oPSz8qQaB9Xh-GhBomsZnZ-AUdPSqTv9
"""

#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input())
    list = []

    while n > 0:
        rm = n % 2
        n = n // 2
        list.append(rm)

    count, result = 0,0

    for i in range(0,len(list)):
        if list[i] == 0:
            count = 0

        else:
            count = count + 1
            result = max(result,count)

    print(result)